# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 19:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carsell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarEvaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluater', models.CharField(default='My Project', max_length=80)),
                ('evaluated', models.CharField(default='My Project', max_length=80)),
                ('published_date', models.DateField(auto_now_add=True, null=True)),
                ('design', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1)),
                ('usability', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(default='', max_length=30)),
                ('usability', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('design', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('average', models.IntegerField(blank=True, default=0)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='evaluate',
            name='user',
        ),
        migrations.AddField(
            model_name='car',
            name='av_design',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='car',
            name='av_usability',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='car',
            name='rating',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.DeleteModel(
            name='Evaluate',
        ),
    ]
